steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE}', '.']
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE}']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image'
  - '${_IMAGE}'
  - '--region'
  - '${_REGION}'
images:
- '${_IMAGE}'
substitutions:
# specify region to avoid 'global'
 _REGION: us-central1
# specify artifact repository (not source repository)
 _REPOSITORY: prj-containers
 _IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}
 _SERVICE_NAME: cloudrun-srv-placeholder
options:
 dynamic_substitutions: true
